COMP: solve issue with conda dependencies on macOS
ipympl and jupyterlab as conda dependencies throws the following error on macOS:
NoPackagesFoundError: Package missing in current osx-64 channels:

passing them as a pip dependency solves the issue